# Generated by Django 5.1 on 2024-11-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("total_listening_time", models.IntegerField(default=0)),
                ("sound_town", models.CharField(default="Unknown", max_length=255)),
                (
                    "listening_character",
                    models.CharField(default="Unknown", max_length=255),
                ),
                ("top_genres", models.JSONField(default=list)),
                ("top_artists", models.JSONField(default=list)),
                ("top_tracks", models.JSONField(default=list)),
                ("genre_persona", models.TextField(blank=True, null=True)),
                ("period", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunitySlideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_date", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_slideshow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotifyWrapped.slideshow",
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_date"],
            },
        ),
        migrations.CreateModel(
            name="SpotifyTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("album_name", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("spotify_url", models.URLField(max_length=500)),
                ("preview_url", models.URLField(blank=True, max_length=500, null=True)),
                ("popularity", models.IntegerField(default=0)),
                ("period", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
