# Generated by Django 5.1 on 2024-11-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotifyWrapped", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_name", models.CharField(max_length=200)),
                ("artist_name", models.CharField(max_length=200)),
                ("album_name", models.CharField(max_length=200)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("spotify_url", models.URLField(max_length=500)),
                ("popularity", models.IntegerField(default=0)),
                ("period", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
