# Generated by Django 4.1.13 on 2024-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyWrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
