# Generated by Django 5.1 on 2024-11-26 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotifyWrapped", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                ("total_listening_time", models.IntegerField(default=0)),
                ("sound_town", models.CharField(default="Unknown", max_length=255)),
                (
                    "listening_character",
                    models.CharField(default="Unknown", max_length=255),
                ),
                ("top_genres", models.JSONField(default=list)),
                ("top_artists", models.JSONField(default=list)),
                ("top_tracks", models.JSONField(default=list)),
                ("period", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
