# Generated by Django 5.1 on 2024-11-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotifyWrapped", "0002_spotifytrack_delete_choice_delete_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytrack",
            name="preview_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
